import type { Metadata } from "next";
import "../../public/style.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
const JotaiProvider = dynamic(() => import("@/providers/jotaiProvider"), {
  ssr: false,
});
import "./globals.css";
import Header from "./_component/nav/Header";
import Footer from "./_component/nav/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#1E1E1E] text-white`}>
        <Header />
        <div className="md:px-10 lg:px-20 px-5">
          <JotaiProvider>{children}</JotaiProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
